redirects:  
    developers-guide/plugin-guidelines/: https://developers.shopware.com/developers-guide/plugin-guidelines/
    guides/integrations-api/store-api-guide: guides/integrations-api
    guides/integrations-api/store-api-guide/register-a-customer: guides/integrations-api
    guides/integrations-api/store-api-guide/search-for-products: guides/integrations-api
    guides/integrations-api/store-api-guide/work-with-the-cart: guides/integrations-api
    guides/integrations-api/store-api-guide/handling-the-payment: guides/integrations-api
    guides/integrations-api/store-api-guide/faq: guides/integrations-api