name: Update ADRs
on: 
  workflow_dispatch:
  schedule:
    - cron: 0 */3 * * *

jobs:
  create-adr-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      - uses: denoland/setup-deno@v1
        with:
          deno-version: "~1.32"

      - run: ./.github/scripts/update-adrs.sh
      - run: ./.github/scripts/migrate.sh ./resources/references/adr/

      - name: Migrate links
        uses: addnab/docker-run-action@v3
        with:
          image: php:8.0
          options: -v ${{ github.workspace }}:/var/www
          run: find ./resources/references/adr/ -name '*.md' -exec php ./.github/scripts/migrate.php {} +

      - uses: peter-evans/create-pull-request@v4
        with:
          add-paths: |
            resources/references/adr/**/*
            resources/references/adr/*.md
            index.md
          author: shopwareBot <example@example.com>
          committer: shopwareBot <example@example.com>
          assignees: Isengo1989
          branch: adr-reference-update
          delete-branch: true
          title: 'Update Architecture Decision Records'
          body: 'Mirrored from: [shopware/shopware](https://github.com/shopware/shopware/tree/trunk)'
  create-code-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      - uses: denoland/setup-deno@v1
        with:
          deno-version: "~1.32"

      - run: ./.github/scripts/update-code-guidelines.sh
      - run: ./.github/scripts/migrate.sh ./resources/guidelines/code/core/

      - name: Migrate links
        uses: addnab/docker-run-action@v3
        with:
          image: php:8.0
          options: -v ${{ github.workspace }}:/var/www
          run: find /resources/guidelines/code/core/ -name '*.md' -exec php ./.github/scripts/migrate.php {} +

      - uses: peter-evans/create-pull-request@v4
        with:
          add-paths: |
            resources/guidelines/code/core/*.md
            index.md
          author: shopwareBot <example@example.com>
          committer: shopwareBot <example@example.com>
          assignees: Isengo1989
          branch: code-guidelines-update
          delete-branch: true
          title: 'Update code guidelines from platform'
          body: 'Mirrored from: [shopware/shopware](https://github.com/shopware/shopware/tree/trunk)'
